### ISSUE TITLE
Ep3: One kanji directly in the text doesn't render in-game

### ISSUE THREAD

**Issue by Kryomancer** [ooa113y/umiproj-wh-tl#3]
Noticed that  this specific line:

https://github.com/ooa113y/umiproj-wh-tl/blob/8e7716d2808a0c8b871c5bb964c6eef011c3b818/story/ep3/wh/umi3_10.txt#L657

shows up in-game as

![image](http://kake.guru/uminekokanji.png)

However, the line

https://github.com/ooa113y/umiproj-wh-tl/blob/8e7716d2808a0c8b871c5bb964c6eef011c3b818/story/ep3/wh/umi3_10.txt#L183

shows up perfectly fine

![image](http://kake.guru/uminekoworks.png)

So I suppose the kanji in the above line should be changed to something like `{p:0:里}` to make it display correctly. Haven't checked the rest of the files for any potential stray kanji.

**Comment by ooa113y** [comment]
Thanks for the report! Yeah, there might be a few of these, as I haven't found a sane way to check for them automatically. Fortunately these tend not to be too big of a deal because it's not like English speakers would find kanji any easier to read than mysterious squares 😆 
I fixed this one. If you find any others, please do bring them up as well.

**Comment by Kryomancer** [comment]
@ooa113y 

> Thanks for the report! Yeah, there might be a few of these, as I haven't found a sane way to check for them automatically. 

I have a bad habit of taking this kind of stuff as a challenge and managed to figure out that there is a fairly good regex solution to finding kanji. Not too many lines in the whole shebang actually contain kanji (or at least it didn't find too many, assuming it works), so checking them for missing markup was fairly easy. I found the following using `` `.*[一-龯].*` `` and applying visual grep to check whether they had any `{}` around:

https://github.com/ooa113y/umiproj-wh-tl/blob/c40be5f6f9f901010276ab9ef28312af01290682/story/ep1/wh/umi1_3.txt#L374
https://github.com/ooa113y/umiproj-wh-tl/blob/c40be5f6f9f901010276ab9ef28312af01290682/story/ep4/wh/umi4_18.txt#L394
https://github.com/ooa113y/umiproj-wh-tl/blob/c40be5f6f9f901010276ab9ef28312af01290682/story/ep5/wh/umi5_4.txt#L344
https://github.com/ooa113y/umiproj-wh-tl/blob/c40be5f6f9f901010276ab9ef28312af01290682/story/ep7/wh/umi7_19.txt#L547

Hope I didn't miss any. I only had the patience of hunting the first one of these down in-game to ensure that it is indeed broken, but logic should dictate that they all are.

Thanks for your good work!

**Comment by ooa113y** [comment]
Holy hell, I have no idea how you got to that regex and why it works, but thanks for finding these! I have fixed all of those.

**Comment by Kryomancer** [comment]
Eh, I just stole these ones I found on a google search: https://gist.github.com/terrancesnyder/1345094

As far as I can tell they seem to be mostly working. I only ran the two topmost against the translation files, didn't find any offenders in the kana one.
