### ISSUE TITLE
More non-rendering special characters & few garbled lines

### ISSUE THREAD

**Issue by Kryomancer** [ooa113y/umiproj-wh-tl#5]
Turns out it's not just kanji giving us problems. I noticed this when I ran into a ☆ in ep3. I tried to figure out some sane way to catch all "special" symbols in the script and landed on the monstrosity of `` `[^{\n]*[^\x00-\x7F—‐‘’èé“”•][^}\n]*` `` regex. I added a few assumed good characters in the middle as exceptions, namely `—‐‘’èé“”` which appear very often so assuming are fine in game. The regex above tries to match any lines with non-ASCII characters that have no { before them and no } after them, this could let a line that has that markup both before and after but not around the offending character through, but I'm assuming that it would be moderately rare. Lots of assumptions here, I know, but anything less tends to blow up with insane amounts of false positives. That at least whittles it down to only 40 results in the story folder, somewhat manageable manually.

I pasted the results of my search here:
https://gist.github.com/Kryomancer/8b5ea08bdb85ef7ed414a4843105fed0

**Things that I checked and don't work in-game:**

- ☆

**Things I haven't checked in-game but are likely worth investigating:**

- ♪ (most of these appear with the `{p:0:♪}` so this is likely broken)
- • (9 of these in umi8_9.txt line 313-321)
- ÷ (3 of these in umi6_10.txt)
- «» (only in umio5.txt)
- 『 (umi4_6.txt)

At this point I think it might be a good idea to just compile a version with all of the above special symbols (along with `—‐‘’èé“”` just to be sure) on any of the first lines in the game and see how they turn out in-game to be able to rule out what is and isn't problematic. I'll have to look into how to compile this thing myself in the future to make checking stuff out less of a chore.

**Lines that are just otherwise garbled and don't work in a text editor either:**

https://github.com/ooa113y/umiproj-wh-tl/blob/12df4610d04c2afbc60c83e629a36df433686d69/story/ep1/wh/umi1_6.txt#L86
https://github.com/ooa113y/umiproj-wh-tl/blob/12df4610d04c2afbc60c83e629a36df433686d69/story/ep1/wh/umi1_6.txt#L326
https://github.com/ooa113y/umiproj-wh-tl/blob/12df4610d04c2afbc60c83e629a36df433686d69/story/ep1/wh/umi1_10.txt#L139
https://github.com/ooa113y/umiproj-wh-tl/blob/12df4610d04c2afbc60c83e629a36df433686d69/story/ep7/wh/umi7_13.txt#L45

I fear this is still nowhere near comprehensive. I'm currently at the end of ep3 (started with it having read 1&2 on the steam version) and will be playing through the rest so I'll keep reporting if I run into anything else that's not displaying right, but it'll take a while. As a silver lining, at least none of these are showstoppers that would make it impossible to enjoy the story.

**Comment by ooa113y** [comment]
Thanks again for reporting these.
Some of these will display fine with the English font, like the math operators and whatnot, while others (the emoji) only render with the Japanese font, so I applied the fixes where relevant.
The `umio_X` files are "omake" content that was created by the Umineko Project people and thus has no Witch-Hunt translation for it as it's exclusive to their version of the game, so anything in those is automatically okay as I didn't modify them from their `en` counterpart.
By the way, you are absolutely free to send pull requests if you'd like. Though I understand if you'd rather let me handle the code itself, it sounds like it'd be faster both for me and for you if you did it yourself, especially since you have figured out most things about how the script works by now. You don't have to do that, but it's just a suggestion.

**Comment by ooa113y** [comment]
In regards to compilation, by far the fastest way would be for you to fork the repo, enable Actions (on the Actions tab) and then click "Build release" on there whenever you want to, well, build a release. The "Build pre-release" option will additionally produce a plain-text version of the full script (with all the code in it) so you can use that as well.
If you want to compile it locally, you can just check out what `main.yml` does in the `.github/workflows` directory, it should be fairly straightforward to understand and get working.

**Comment by Kryomancer** [comment]
Thanks, you're absolutely right that I could be PR'ing any obvious small fixes, I'll set that up if I find anything else, though for now I think I've found mostly everything that I can with just automated searching alone. I'll keep my eyes open if anything else pops up while playing.
